# Dependencies
markdown:         kramdown
highlighter:      Rouge

# Permalinks
permalink:        pretty

# Setup
title:            Rahel Zimmermann
tagline:          'Rahel Zimmermann'
description:      'I am based in Switzerland working towards my PhD under the supervision of  <a href="https://www.unige.ch/droit/index.php?cID=1029" target="_blank">Prof. Mbengue</a>. I also work as a Legal Counsel in an Environmental Management Consultancy'
url: https://rahelzimmermann.github.io/rahelzimmermann.github.io/
baseurl: /

author:
name:           'Rahel Zimmermann'
#  url:            https://rahelzimmermann.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/rahelzimmermann/rahelzimmermann.github.io/blob/master/cv_rah_zimmermann.pdf
  
  
plugins:
  - jekyll-paginate
  - jekyll-gist